apiVersion: v1
kind: Service
metadata:
  name: pihole-service-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: pihole
  type: LoadBalancer
  externalIPs:
  - 192.168.0.64
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  - name: dns
    port: 53
    targetPort: 53
    protocol: TCP