apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data
  namespace: pihole
  labels:
    app: pihole
    component: pihole
    tier: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain